spring:
  datasource:
    url: jdbc:h2:mem:db;INIT=RUNSCRIPT FROM 'classpath:insert.sql'
    username: sa
    password:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
